apiVersion: v1
kind: ReplicationController
metadata:
  name: k8test-controller
spec:
  replicas: 2
  selector:
    app: k8test
  template:
    metadata:
      labels:
        app: k8test
    spec:
      containers:
        - image: ivanbrovenko/k8test
          name: k8test
          ports:
            - containerPort: 8080
---
# Node Port Service For SpringApp
apiVersion: v1
kind: Service
metadata:
  name: k8test
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: k8test
---